### ISSUE TITLE
It is possible to create an event with registration without 'registration_opens'. Gives 500.

### ISSUE THREAD

**Issue by Northo** [Nabla-NTNU/nablaweb#369]
Creating an event with registration, but no `registration_opens`, produces 500.
We have logic making sure that the datetimes makes sense, ie. registration opens before it closes, but apparently no check to see if it is set, when registration is set.

Should be a simple case of adding some validation. Maybe not a first issue, but a good second issue.

Tip: Look at how to overwrite `save()`.

```
2020-01-29 16:51:06,692 Internal Server Error: /arrangement/1362-webkom-tester-server
Traceback (most recent call last):
  File "/var/websites/nablaweb/.local/share/virtualenvs/nablaweb-5dOjcOIa/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/websites/nablaweb/.local/share/virtualenvs/nablaweb-5dOjcOIa/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/websites/nablaweb/.local/share/virtualenvs/nablaweb-5dOjcOIa/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/websites/nablaweb/.local/share/virtualenvs/nablaweb-5dOjcOIa/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/websites/nablaweb/.local/share/virtualenvs/nablaweb-5dOjcOIa/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/var/websites/nablaweb/.local/share/virtualenvs/nablaweb-5dOjcOIa/lib/python3.6/site-packages/django/views/generic/detail.py", line 107, in get
    context = self.get_context_data(object=self.object)
  File "/srv/nablaweb/nablapps/events/views.py", line 215, in get_context_data
    event._assert_user_allowed_to_register(user)
  File "/srv/nablaweb/nablapps/events/models/mixins.py", line 149, in _assert_user_allowed_to_register
    elif not self.registration_open():
  File "/srv/nablaweb/nablapps/events/models/mixins.py", line 132, in registration_open
    return self.registration_has_started() and datetime.now() < self.registration_deadline
  File "/srv/nablaweb/nablapps/events/models/mixins.py", line 128, in registration_has_started
    return self.registration_required and self.registration_start < datetime.now()
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.datetime'
```

**Comment by martkjoh** [comment]
Fixed by 8ce3b7766fcd1143b637559def7bf3f6bafcfb75
