### ISSUE TITLE
Failed to run `seed`

### ISSUE THREAD

**Issue by Northo** [Nabla-NTNU/nablaweb#443]
Running `seed` failes.
Traceback:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/user/.local/share/virtualenvs/nablaweb-4l-K7Rqm/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/user/.local/share/virtualenvs/nablaweb-4l-K7Rqm/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/.local/share/virtualenvs/nablaweb-4l-K7Rqm/lib/python3.6/site-packages/django/core/management/__init__.py", line 244, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/user/.local/share/virtualenvs/nablaweb-4l-K7Rqm/lib/python3.6/site-packages/django/core/management/__init__.py", line 37, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/home/user/.pyenv/versions/3.6.12/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/nablaweb/nablapps/core/management/commands/seed.py", line 19, in <module>
    from faker import Factory
ModuleNotFoundError: No module named 'faker'
```

Probably just a missing dependency.

**Comment by Amund211** [comment]
We made `faker` and some other packages dev-requirements a while ago. `pipenv sync --dev` should fix that.
