### ISSUE TITLE
Error in album

### ISSUE THREAD

**Issue by Amund211** [Nabla-NTNU/nablaweb#458]
There seems to be an error in album. A user is supposedly having issues uploading a lot of images (~100) at once.
This seems to be the related stack trace, and it was repeated about five times:

```
2021-03-10 21:26:23,675 Internal Server Error: /admin/album/album/66/change/
Traceback (most recent call last):
  File "/var/websites/nablaweb/.local/share/virtualenvs/nablaweb-5dOjcOIa/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/websites/nablaweb/.local/share/virtualenvs/nablaweb-5dOjcOIa/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/websites/nablaweb/.local/share/virtualenvs/nablaweb-5dOjcOIa/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/websites/nablaweb/.local/share/virtualenvs/nablaweb-5dOjcOIa/lib/python3.6/site-packages/django/contrib/admin/options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/var/websites/nablaweb/.local/share/virtualenvs/nablaweb-5dOjcOIa/lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/var/websites/nablaweb/.local/share/virtualenvs/nablaweb-5dOjcOIa/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/var/websites/nablaweb/.local/share/virtualenvs/nablaweb-5dOjcOIa/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "/var/websites/nablaweb/.local/share/virtualenvs/nablaweb-5dOjcOIa/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1641, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/var/websites/nablaweb/.local/share/virtualenvs/nablaweb-5dOjcOIa/lib/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/var/websites/nablaweb/.local/share/virtualenvs/nablaweb-5dOjcOIa/lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/var/websites/nablaweb/.local/share/virtualenvs/nablaweb-5dOjcOIa/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/var/websites/nablaweb/.local/share/virtualenvs/nablaweb-5dOjcOIa/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1565, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/srv/nablaweb/nablapps/core/admin.py", line 30, in save_model
    super().save_model(request, obj, form, change)
  File "/var/websites/nablaweb/.local/share/virtualenvs/nablaweb-5dOjcOIa/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1081, in save_model
    obj.save()
  File "/var/websites/nablaweb/.local/share/virtualenvs/nablaweb-5dOjcOIa/lib/python3.6/site-packages/mptt/models.py", line 951, in save
    self, parent, 'last-child', save=False)
  File "/var/websites/nablaweb/.local/share/virtualenvs/nablaweb-5dOjcOIa/lib/python3.6/site-packages/mptt/managers.py", line 71, in wrapped
    return method(self, *args, **kwargs)
  File "/var/websites/nablaweb/.local/share/virtualenvs/nablaweb-5dOjcOIa/lib/python3.6/site-packages/mptt/managers.py", line 590, in _move_node
    self._move_root_node(node, target, position)
  File "/var/websites/nablaweb/.local/share/virtualenvs/nablaweb-5dOjcOIa/lib/python3.6/site-packages/mptt/managers.py", line 1246, in _move_root_node
    raise InvalidMove(_('A node may not be made a child of itself.'))
mptt.exceptions.InvalidMove: En node kan ikke være barn av seg selv.
```

**Comment by alexarntzen** [comment]
This is an error that occurs when users try to make an album an sub-album of itself. So user error

**Comment by kaprests** [comment]
Do we know how the user tried to upload the images? I didn't think we (yet) had support for uploading more than one image at the time.

**Comment by Northo** [comment]
> This is an error that occurs when users try to make an album an sub-album of itself. So user error

"User error" is the best get out of jail free-card in programming:)

**Comment by alexarntzen** [comment]
Ok I will make sure that users can not make albums their own parents.
