### ISSUE TITLE
Rombookingsskjema funkar ikkje

### ISSUE THREAD

**Issue by jonathanKjorlaug** [Nabla-NTNU/nablaweb#686]
Når ein prøvar å sende rombooking på hemmer får ein ein "Error 500", følgjande stack-

smtplib.SMTPRecipientsRefused: {'koordinator@nabla.no': (550, b'5.1.1 <koordinator@nabla.no>: Recipient address rejected: User unknown in local recipient table')}
2024-10-13 10:36:45,887 Internal Server Error: /contact/rombooking/
Traceback (most recent call last):
  File "/var/websites/nablaweb/.local/share/virtualenvs/nablaweb-5dOjcOIa/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/var/websites/nablaweb/.local/share/virtualenvs/nablaweb-5dOjcOIa/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/nablaweb/nablapps/contact/views.py", line 108, in roombooking
    send_mail(subject, message, email, [send_to], fail_silently=False)
  File "/var/websites/nablaweb/.local/share/virtualenvs/nablaweb-5dOjcOIa/lib/python3.10/site-packages/django/core/mail/__init__.py", line 61, in send_mail
    return mail.send()
  File "/var/websites/nablaweb/.local/share/virtualenvs/nablaweb-5dOjcOIa/lib/python3.10/site-packages/django/core/mail/message.py", line 284, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/var/websites/nablaweb/.local/share/virtualenvs/nablaweb-5dOjcOIa/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 109, in send_messages
    sent = self._send(message)
  File "/var/websites/nablaweb/.local/share/virtualenvs/nablaweb-5dOjcOIa/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 125, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
  File "/usr/lib/python3.10/smtplib.py", line 901, in sendmail
    raise SMTPRecipientsRefused(senderrs)
smtplib.SMTPRecipientsRefused: {'koordinator@nabla.no': (550, b'5.1.1 <koordinator@nabla.no>: Recipient address rejected: User unknown in local recipient table')}
 `

**Comment by Joliv3r** [comment]
The issue seemed to be Postfix assuming `@nabla.no` was a local address and therefore failed when not finding the user in the local recipient table.
